BASE_URL = "https://stellarburgers.nomoreparties.site/api"
REGISTER_URL = f"{BASE_URL}/auth/register"
AUTH_URL = f"{BASE_URL}/auth/login"
GET_INGREDIENTS = f"{BASE_URL}/ingredients"
ORDERS = f"{BASE_URL}/orders"
USER_INFO = f"{BASE_URL}/auth/user"
