BASE_URL = "https://stellarburgers.nomoreparties.site/api"
REGISTER_URL = f"{BASE_URL}/auth/register"
AUTH_URL = f"{BASE_URL}/auth/login"
GET_INGREDIENTS = f"{BASE_URL}/ingredients"
CREATE_ORDER = f"{BASE_URL}/orders"
